package de.hs.tpe.blatt2;

enum Becher {
	ERDBEERBECHER,NUSSBECHER,PINOCCIO,ALASKABECHER, AMARENABECHER,SPAGETTIEIS,KROKANTBECHER,PIRSICHMELBA, 
	BANANENSPLIT, JOGURTBECHER,EXOTIKBECHER,SCHOKOLADENBECHER;
	

}
