package de.hs.tpe.blatt2;

enum Becher {
	ERDBEERBECHER,NUSSBECHER,ALASKABECHER, AMARENABECHER,KROKANTBECHER,PIRSICHMELBA, 
	BANANENSPLIT, JOGURTBECHER,EXOTIKBECHER,SCHOKOLADENBECHER,SPAGETTIEIS,PINOCCIO,WAFFEL;
	

}
